# This is a basic workflow to help you get started with Actions

name: Scraping Diariov2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
  
  #push:
  #  branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
       #   echo Add other actions to build,
       #   echo test, and deploy your project.



      #          - name: Clonar el repositorio
      #  uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

     #name: tasa_pasiva

      - name: Ejecutar scraping
        run: python tasa_pasiva.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push

     #name: empleo_usa
     
      - name: Ejecutar scraping
        run: python empleo_usa.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push


     #name: tipo_cambio
     
      - name: Ejecutar scraping
        run: python tipo_cambio.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push


     #name: tasas_usa
     
      - name: Ejecutar scraping
        run: python tasas_usa.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push



     #name: indice_bonos
     
      - name: Ejecutar scraping
        run: python indice_bonos.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push

     #name: FED_inflacion
     
      - name: Ejecutar scraping
        run: python FED_inflacion.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Hacer commit y push del historial
        run: |
          git add historial/*.csv
          git commit -m "Agregar archivo generado el $(date +'%Y-%m-%d')" || echo "Nada que commitear"
          git push
  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
